#!/bin/bash
# A bash script that helps me switch between tmux sessions.
# TODO
# 1. check if file already exists
# 2. write this in Go :)

# function to prompt the user for a filename
get_session_name() {
	read -p "Enter a session name: " session
	echo "$session"
}

# function to create and open a file in the specified directory
open_session() {
	tmux detach-client
	tmux new-session -A -s $session
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	session=$(get_session_name)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one session name separated by dashes."
	echo "Example: sess home"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	session=$1
fi

open_session
